image: python:2.7
env:
  - PYTHONPATH=picture_clerk
script:
  - sudo apt-get install -y python-pyexiv2
  - pip install -r requirements.txt --use-mirrors
  - nosetests
notify:
  email:
    recipients:
      - matthias@grueter.name
